In [63]:
import os

print(os.getcwd())

c:\projects\Game-Recommendation-System\notebook

In [64]:
import pandas as pd

recommendations = pd.read_csv("../data/recommendations.csv")
games = pd.read_csv("../data/games.csv")
users = pd.read_csv("../data/users.csv")
print(recommendations.head())
print(games.head())
print(users.head())

    app_id  helpful  funny        date  is_recommended  hours  user_id  \
0   975370        0      0  2022-12-12            True   36.3    51580
1   304390        4      0  2017-02-17           False   11.5     2586
2  1085660        2      0  2019-11-17            True  336.5   253880
3   703080        0      0  2022-09-23            True   27.4   259432
4   526870        0      0  2021-01-10            True    7.9    23869

   review_id
0          0
1          1
2          2
3          3
4          4
   app_id                              title date_release   win    mac  linux  \
0   13500  Prince of Persia: Warrior Within™   2008-11-21  True  False  False
1   22364            BRINK: Agents of Change   2011-08-03  True  False  False
2  113020       Monaco: What's Yours Is Mine   2013-04-24  True   True   True
3  226560                 Escape Dead Island   2014-11-18  True  False  False
4  249050            Dungeon of the ENDLESS™   2014-10-27  True   True  False

          rating  positive_ratio  user_reviews  price_final  price_original  \
0  Very Positive              84          2199         9.99            9.99
1       Positive              85            21         2.99            2.99
2  Very Positive              92          3722        14.99           14.99
3          Mixed              61           873        14.99           14.99
4  Very Positive              88          8784        11.99           11.99

   discount  steam_deck
0       0.0        True
1       0.0        True
2       0.0        True
3       0.0        True
4       0.0        True
    user_id  products  reviews
0   7360263       359        0
1  14020781       156        1
2   8762579       329        4
3   4820647       176        4
4   5167327        98        2

In [65]:
gamesgenres = pd.read_csv("../data/games_inc.csv")

In [66]:
correct_columns = [
    'AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU',
    'Required age', 'Price', 'Discount', 'DLC count', 'About the game',
    'Supported languages', 'Full audio languages', 'Reviews', 'Header image',
    'Website', 'Support url', 'Support email', 'Windows', 'Mac', 'Linux',
    'Metacritic score', 'Metacritic url', 'User score', 'Positive', 'Negative',
    'Score rank', 'Achievements', 'Recommendations', 'Notes',
    'Average playtime forever', 'Average playtime two weeks',
    'Median playtime forever', 'Median playtime two weeks',
    'Developers', 'Publishers', 'Categories', 'Genres', 'Tags',
    'Screenshots', 'Movies'
]

gamesgenres = pd.read_csv(
    "../data/games_inc.csv",
    header=0,          # 기존 헤더 줄은 버리고
    names=correct_columns  # 이 이름들을 강제로 매핑
)

print(gamesgenres.shape)  # (125855, 40) 이 나오면 정상

(125855, 40)

In [67]:
gamesgenres.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,About the game,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [68]:
print(gamesgenres.columns.tolist())

['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU', 'Required age', 'Price', 'Discount', 'DLC count', 'About the game', 'Supported languages', 'Full audio languages', 'Reviews', 'Header image', 'Website', 'Support url', 'Support email', 'Windows', 'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score', 'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations', 'Notes', 'Average playtime forever', 'Average playtime two weeks', 'Median playtime forever', 'Median playtime two weeks', 'Developers', 'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies']

In [69]:
gamesgenres.info()
gamesgenres.describe()
gamesgenres.columns
gamesgenres.head()

<class 'pandas.DataFrame'>
RangeIndex: 125855 entries, 0 to 125854
Data columns (total 40 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   AppID                       125855 non-null  int64
 1   Name                        125854 non-null  str
 2   Release date                125855 non-null  str
 3   Estimated owners            125855 non-null  str
 4   Peak CCU                    125855 non-null  int64
 5   Required age                125855 non-null  int64
 6   Price                       125855 non-null  float64
 7   Discount                    125855 non-null  int64
 8   DLC count                   125855 non-null  int64
 9   About the game              117393 non-null  str
 10  Supported languages         125855 non-null  str
 11  Full audio languages        125855 non-null  str
 12  Reviews                     12181 non-null   str
 13  Header image                125774 non-null  str
 14  Website                     50520 non-null   str
 15  Support url                 55295 non-null   str
 16  Support email               103225 non-null  str
 17  Windows                     125855 non-null  bool
 18  Mac                         125855 non-null  bool
 19  Linux                       125855 non-null  bool
 20  Metacritic score            125855 non-null  int64
 21  Metacritic url              4258 non-null    str
 22  User score                  125855 non-null  int64
 23  Positive                    125855 non-null  int64
 24  Negative                    125855 non-null  int64
 25  Score rank                  40 non-null      float64
 26  Achievements                125855 non-null  int64
 27  Recommendations             125855 non-null  int64
 28  Notes                       23310 non-null   str
 29  Average playtime forever    125855 non-null  int64
 30  Average playtime two weeks  125855 non-null  int64
 31  Median playtime forever     125855 non-null  int64
 32  Median playtime two weeks   125855 non-null  int64
 33  Developers                  117406 non-null  str
 34  Publishers                  116933 non-null  str
 35  Categories                  116889 non-null  str
 36  Genres                      117432 non-null  str
 37  Tags                        83353 non-null   str
 38  Screenshots                 119828 non-null  str
 39  Movies                      0 non-null       float64
dtypes: bool(3), float64(3), int64(15), str(19)
memory usage: 35.9 MB

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,About the game,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [70]:
meta = gamesgenres[
    [
        "AppID",
        "Name",
        "Genres",
        "Tags",
        "Categories",
        "About the game"
    ]
].copy()

In [71]:
meta.info()
meta.describe()
meta.columns

<class 'pandas.DataFrame'>
RangeIndex: 125855 entries, 0 to 125854
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   AppID           125855 non-null  int64
 1   Name            125854 non-null  str
 2   Genres          117432 non-null  str
 3   Tags            83353 non-null   str
 4   Categories      116889 non-null  str
 5   About the game  117393 non-null  str
dtypes: int64(1), str(5)
memory usage: 5.8 MB

Index(['AppID', 'Name', 'Genres', 'Tags', 'Categories', 'About the game'], dtype='str')

In [72]:
print(meta.isnull().sum())

AppID                 0
Name                  1
Genres             8423
Tags              42502
Categories         8966
About the game     8462
dtype: int64

In [73]:
meta[meta['Name'].isnull()]

,AppID,Name,Genres,Tags,Categories,About the game
44432,396420,NaN,NaN,NaN,NaN,Spookeningは3Dの恐怖ゲームで、あなたは毎夜に死んでゴーストとして復活します。 村...

In [74]:
meta = meta.dropna(subset=["Name"])

meta_cols = ["Genres", "Tags", "Categories", "About the game"]

meta = meta.dropna(subset=meta_cols, thresh=2)

meta.head()

,AppID,Name,Genres,Tags,Categories,About the game
1,496350,Supipara - Chapter 1 Spring Has Come!,Adventure,"Adventure,Visual Novel,Anime,Cute","Single-player,Steam Trading Cards,Steam Cloud,...","Springtime, April: when the cherry trees come ..."
2,1034400,Mystery Solitaire The Black Raven,Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...","Single-player,Family Sharing","Immerse yourself in the most beloved, mystical..."
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Casual,Indie,Simulation",NaN,"Single-player,Steam Achievements,Family Sharing","synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ..."
4,3631080,Maze Quest VR,"Action,Early Access",NaN,"Single-player,VR Only,Steam Leaderboards,Famil...",Its not just a Maze; its a Quest! Enter the ca...
5,1654170,Agony VR,"Action,Adventure",NaN,"Single-player,Tracked Controller Support,VR On...",A JOURNEY THROUGH HELL! Explore the most terri...

추천 점수 계산 단계에서 메타데이터 개수에 따라 가중치를 적용한다. 메타데이터가 모두 없는 게임은 제거하고, 나머지는 메타데이터 완전성에 따라 추천 점수를 보정한다.

메타데이터 4개 → Weight = 1.0
메타데이터 3개 → Weight = 0.95
메타데이터 2개 → Weight = 0.80
메타데이터 1개 → Weight = 0.60
메타데이터 0개 → 제거

최종 추천 점수 = Cosine Similarity × Weight

In [75]:
meta["Genres"] = meta["Genres"].fillna("")
meta["Categories"] = meta["Categories"].fillna("")
meta["About the game"] = meta["About the game"].fillna("")
meta["Tags"] = meta["Tags"].fillna("")

In [ ]:
# 메타데이터가 2개 이상 있는 행만 유지
meta = meta.dropna(subset=meta_cols, thresh=3)

meta.head()
meta.info()

<class 'pandas.DataFrame'>
Index: 117560 entries, 1 to 125854
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   AppID           117560 non-null  int64
 1   Name            117560 non-null  str
 2   Genres          117560 non-null  str
 3   Tags            117560 non-null  str
 4   Categories      117560 non-null  str
 5   About the game  117560 non-null  str
dtypes: int64(1), str(5)
memory usage: 6.3 MB

In [80]:
meta["Name"].duplicated().sum()

np.int64(1174)

In [88]:
# AppID 중복 제거
meta.drop_duplicates(subset=["AppID"], inplace=True)
meta[meta["Name"].duplicated(keep=False)].sort_values("Name")
meta["Name"].duplicated().sum()

np.int64(1174)

In [77]:
print(meta.columns.tolist())

['AppID', 'Name', 'Genres', 'Tags', 'Categories', 'About the game']

In [78]:
meta.iloc[0]

AppID                                                        496350
Name                          Supipara - Chapter 1 Spring Has Come!
Genres                                                    Adventure
Tags                              Adventure,Visual Novel,Anime,Cute
Categories        Single-player,Steam Trading Cards,Steam Cloud,...
About the game    Springtime, April: when the cherry trees come ...
Name: 1, dtype: object

In [89]:
meta["About the game"].str.len().describe()

count    117560.000000
mean       1299.526803
std        1118.275908
min           0.000000
25%         680.000000
50%        1067.000000
75%        1634.000000
max       89665.000000
Name: About the game, dtype: float64

In [ ]:
meta.to_csv("../data/meta_preprocessed.csv", index=False)

In [101]:
# 사용할 컬럼 합치기
meta["combined_features"] = (
    meta["Genres"].str.replace(",", " ", regex=False) + " " +
    meta["Tags"].str.replace(",", " ", regex=False) + " " +
    meta["Categories"].str.replace(",", " ", regex=False)
)

print(meta["combined_features"].head())

meta.to_csv("../data/meta_preprocessed.csv", index=False)

1                                                                                 Adventure Adventure Visual Novel Anime Cute Single-player Steam Trading Cards Steam Cloud Family Sharing
2    Casual Casual Card Game Solitaire Puzzle Hidden Object 2D Colorful Stylized Logic Mystery Atmospheric Family Friendly PvE Tutorial Singleplayer Tabletop Single-player Family Sharing
3                                                                                                                 Casual Indie Simulation  Single-player Steam Achievements Family Sharing
4                                                                                                             Action Early Access  Single-player VR Only Steam Leaderboards Family Sharing
5                                                                                                        Action Adventure  Single-player Tracked Controller Support VR Only Family Sharing
Name: combined_features, dtype: str

In [96]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words="english",
    lowercase=True
)

tfidf_matrix = tfidf.fit_transform(meta["combined_features"])

print(tfidf_matrix.shape)

(117560, 544)

In [97]:
len(tfidf.get_feature_names_out())
tfidf.get_feature_names_out()

array(['1980s', '1990', '2d', '360', '3d', '40k', '4x', '5d', '6dof',
       'abstract', 'access', 'accounting', 'achievements', 'action',
       'addictive', 'adjustable', 'adventure', 'agriculture', 'aliens',
       'alternate', 'alternatives', 'ambient', 'america', 'american',
       'animation', 'anime', 'anti', 'anytime', 'apocalyptic', 'app',
       'arcade', 'archery', 'arena', 'artificial', 'arts', 'assassin',
       'asymmetric', 'asynchronous', 'atmospheric', 'attack', 'atv',
       'audio', 'auto', 'automation', 'automobile', 'available',
       'awkward', 'base', 'baseball', 'based', 'basketball', 'batman',
       'battle', 'battler', 'beat', 'beautiful', 'benchmark', 'bikes',
       'birds', 'bit', 'blood', 'bmx', 'board', 'book', 'boomer', 'boss',
       'bowling', 'boxing', 'builder', 'building', 'bullet', 'camera',
       'campaign', 'capitalism', 'captions', 'card', 'cards', 'cartoon',
       'cartoony', 'casual', 'cats', 'character', 'chat', 'cheat',
       'chess', 'choices', 'choose', 'cinematic', 'city', 'class',
       'classic', 'click', 'clicker', 'cloud', 'coding', 'cold',
       'collectathon', 'collectibles', 'collector', 'colony', 'color',
       'colorful', 'combat', 'comedy', 'comfort', 'comic', 'commentary',
       'competitive', 'conspiracy', 'content', 'control', 'controller',
       'controls', 'conversation', 'cooking', 'cozy', 'craft', 'crafting',
       'crawler', 'creature', 'cricket', 'crime', 'croft', 'cross',
       'crowdfunded', 'crpg', 'cult', 'custom', 'customization', 'cute',
       'cyberpunk', 'cycling', 'dark', 'dating', 'death', 'deckbuilder',
       'deckbuilding', 'deduction', 'defense', 'demons', 'design',
       'destruction', 'detective', 'development', 'dice', 'difficult',
       'difficulty', 'dinosaurs', 'diplomacy', 'documentary', 'dog',
       'dragons', 'drama', 'drawn', 'driving', 'dungeon', 'dungeons',
       'dwarf', 'dynamic', 'dystopian', 'early', 'economy', 'editing',
       'editor', 'education', 'electronic', 'elf', 'em', 'emotional',
       'enabled', 'endings', 'epic', 'episodic', 'escape', 'events',
       'experience', 'experimental', 'exploration', 'extraction', 'faith',
       'family', 'fantasy', 'farming', 'fast', 'feature', 'female', 'fi',
       'fiction', 'fighter', 'fighting', 'film', 'fishing', 'flight',
       'fmv', 'football', 'foreign', 'fox', 'fps', 'free', 'friendly',
       'funny', 'futuristic', 'gambling', 'game', 'gamemaker', 'games',
       'gaming', 'generation', 'god', 'golf', 'gore', 'gothic', 'grand',
       'graphics', 'great', 'grid', 'gun', 'hack', 'hacking', 'hand',
       'hardware', 'hdr', 'heist', 'hell', 'hentai', 'hero', 'hex',
       'hidden', 'historical', 'history', 'hl2', 'hobby', 'hockey',
       'horror', 'horses', 'humor', 'hunting', 'idler', 'ii',
       'illuminati', 'illustration', 'immersive', 'includes', 'indie',
       'input', 'instrumental', 'intelligence', 'intentionally',
       'interactive', 'inventory', 'investigation', 'isometric', 'jet',
       'job', 'jrpg', 'jump', 'keeper', 'keyboard', 'kickstarter', 'lan',
       'lara', 'leaderboards', 'lego', 'lemmings', 'level', 'lgbtq',
       'life', 'like', 'linear', 'lite', 'local', 'logic', 'loot',
       'looter', 'lore', 'lovecraftian', 'machine', 'magic', 'mahjong',
       'management', 'manipulation', 'mars', 'martial', 'massively',
       'masterpiece', 'match', 'matching', 'matter', 'mature', 'mechs',
       'medical', 'medieval', 'memes', 'menus', 'metroidvania',
       'military', 'mini', 'minigames', 'minimalist', 'mining', 'mmo',
       'mmorpg', 'moba', 'mod', 'moddable', 'modeling', 'modern', 'mods',
       'motocross', 'motorbike', 'mouse', 'movement', 'movie', 'multi',
       'multiplayer', 'multiple', 'music', 'musou', 'mystery',
       'mythology', 'narrated', 'narration', 'narrative', 'nature',
       'naval', 'ninja', 'noir', 'nonlinear', 'nostalgia',
       'notifications', 'novel', 'nsfw', 'nudity', 'object', 'offroad',
       'old', 'online', 'op', 'open', 'option', 'options', 'otome',
       'outbreak', 'paced', 'parkour', 'parody', 'partial', 'party',
       'pause', 'perma', 'person', 'philosophical', 'phone', 'photo',
       'physics', 'pinball', 'pirates', 'pixel', 'platform', 'platformer',
       'play', 'playable', 'player', 'point', 'political', 'politics',
       'pool', 'post', 'precision', 'procedural', 'production',
       'programming', 'protagonist', 'psychedelic', 'psychological',
       'publishing', 'purchases', 'puzzle', 'pve', 'pvp', 'quick',
       'racing', 'rails', 'real', 'realistic', 'reboot', 'relaxing',
       'remake', 'remote', 'replay', 'require', 'resource', 'retro',
       'rhythm', 'rich', 'robots', 'rock', 'rogue', 'roguelike',
       'roguevania', 'romance', 'rome', 'room', 'royale', 'rpg',
       'rpgmaker', 'rts', 'rugby', 'runner', 'rush', 'sailing', 'sandbox',
       'satire', 'save', 'scare', 'school', 'sci', 'science', 'score',
       'screen', 'scroller', 'sdk', 'sequel', 'sexual', 'shared',
       'sharing', 'shoot', 'shooter', 'shop', 'short', 'silent', 'sim',
       'simulation', 'simulator', 'single', 'singleplayer', 'size',
       'skateboarding', 'skating', 'skiing', 'slash', 'sniper', 'snooker',
       'snow', 'snowboarding', 'soccer', 'social', 'software', 'sokoban',
       'solitaire', 'souls', 'sound', 'soundtrack', 'source', 'space',
       'spaceships', 'spectacle', 'speech', 'spelling', 'split', 'sports',
       'stats', 'stealth', 'steam', 'steampunk', 'steamvr', 'stereo',
       'stick', 'story', 'strategy', 'stylized', 'submarine', 'subtitle',
       'superhero', 'supernatural', 'support', 'supported', 'surreal',
       'surround', 'survival', 'swordplay', 'tablet', 'tabletop',
       'tactical', 'tactics', 'tanks', 'team', 'tennis', 'text',
       'thriller', 'tile', 'time', 'timed', 'timeline', 'touch', 'tower',
       'tracked', 'trackir', 'trading', 'traditional', 'training',
       'trains', 'transhumanism', 'transportation', 'travel', 'trivia',
       'turn', 'tutorial', 'tv', 'twin', 'typing', 'underground',
       'underwater', 'unforgiving', 'utilities', 'value', 'valve',
       'vampire', 'vehicular', 'video', 'vikings', 'villain', 'violent',
       'vision', 'visual', 'voice', 'volleyball', 'volume', 'voxel', 'vr',
       'walking', 'war', 'wargame', 'warhammer', 'web', 'werewolves',
       'western', 'wholesome', 'word', 'workshop', 'world', 'wrestling',
       'written', 'zombies'], dtype=object)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

MemoryError: Unable to allocate 103. GiB for an array with shape (117560, 117560) and data type float64