In [1]:
import pandas as pd

correct_columns = [
    'app_id', 'Name', 'Release date', 'Estimated owners', 'Peak CCU',
    'Required age', 'Price', 'Discount', 'DLC count', 'About the game',
    'Supported languages', 'Full audio languages', 'Reviews', 'Header image',
    'Website', 'Support url', 'Support email', 'Windows', 'Mac', 'Linux',
    'Metacritic score', 'Metacritic url', 'User score', 'Positive', 'Negative',
    'Score rank', 'Achievements', 'Recommendations', 'Notes',
    'Average playtime forever', 'Average playtime two weeks',
    'Median playtime forever', 'Median playtime two weeks',
    'Developers', 'Publishers', 'Categories', 'Genres', 'Tags',
    'Screenshots', 'Movies'
]

gamesgenres = pd.read_csv(
    "../data/games_inc.csv",
    header=0,          # 기존 헤더 줄은 버리고
    names=correct_columns  # 이 이름들을 강제로 매핑
)

print(gamesgenres.shape)  # (125855, 40) 이 나오면 정상
recommendations = pd.read_csv("../data/recommendations.csv")
print(recommendations.shape)
games_recs_merged = pd.merge(gamesgenres, recommendations, on='app_id', how='inner')

print(games_recs_merged.shape)
games_recs_merged.head()
games_recs_merged.to_csv(
    "data/games_recs_merged.csv",
    index=False,
    encoding="utf-8-sig"
)

(125855, 40)
(41154794, 8)
(40230954, 47)

OSError: Cannot save file into a non-existent directory: 'data'

In [15]:
user_review_counts = games_recs_merged.groupby('user_id').size().reset_index(name='review_count')
user_review_counts = user_review_counts.sort_values('review_count', ascending=False)

print(user_review_counts.shape)
user_review_counts.head(10)

(13589197, 2)

           user_id  review_count
11152009  11764552          5826
4720056    5112758          3933
11046188  11656130          3758
5261744    5669734          3366
10946125  11553593          3209
4990278    5390510          2853
4149867    4457971          2664
4018422    4318160          2647
545448      574944          2587
1293097    1365585          2327

In [7]:
print(user_review_counts['review_count'].describe())
print(user_review_counts['review_count'].quantile([0.5, 0.9, 0.95, 0.99, 0.999]))

count    1.358920e+07
mean     2.960510e+00
std      7.959970e+00
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      3.000000e+00
max      5.826000e+03
Name: review_count, dtype: float64
0.500     1.0
0.900     6.0
0.950     9.0
0.990    25.0
0.999    78.0
Name: review_count, dtype: float64

In [11]:
lower_bound = 10
upper_bound = 78  # 99.9 percentile 근사값 (봇/이상치 배제)

eligible_users = user_review_counts[
    (user_review_counts['review_count'] >= lower_bound) &
    (user_review_counts['review_count'] <= upper_bound)
]
print(f"평가 대상 유저 수: {len(eligible_users):,}")

평가 대상 유저 수: 647,035

In [13]:
eval_df = games_recs_merged[
    games_recs_merged["user_id"].isin(eligible_users["user_id"])
]

In [22]:
import pandas as pd

pd.set_option("display.max_columns", None)  # 모든 컬럼 표시
pd.set_option("display.max_colwidth", None) # 긴 문자열도 생략하지 않음
pd.set_option("display.width", None)        # 화면 너비 제한 해제

games_recs_merged.head()

print(eval_df.head(7))

    app_id                                   Name  Release date  \
1   496350  Supipara - Chapter 1 Spring Has Come!  Jul 29, 2016
2   496350  Supipara - Chapter 1 Spring Has Come!  Jul 29, 2016
4   496350  Supipara - Chapter 1 Spring Has Come!  Jul 29, 2016
5   496350  Supipara - Chapter 1 Spring Has Come!  Jul 29, 2016
10  496350  Supipara - Chapter 1 Spring Has Come!  Jul 29, 2016
11  496350  Supipara - Chapter 1 Spring Has Come!  Jul 29, 2016
12  496350  Supipara - Chapter 1 Spring Has Come!  Jul 29, 2016

   Estimated owners  Peak CCU  Required age  Price  Discount  DLC count  \
1         0 - 20000         0             0   5.24        65          0
2         0 - 20000         0             0   5.24        65          0
4         0 - 20000         0             0   5.24        65          0
5         0 - 20000         0             0   5.24        65          0
10        0 - 20000         0             0   5.24        65          0
11        0 - 20000         0             0   5.24        65          0
12        0 - 20000         0             0   5.24        65          0

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                About the game  \
1   Springtime, April: when the cherry trees come into full bloom. The protagonist Yukinari Sanada has returned to his hometown in Kanagawa Prefecture, Kamakura City, for the first time in seven years, and is greeted by his older cousin Sakura Narumi (complete with maid outfit). He wanted to live in peace, but his life at the academy placed on the coastlands becomes bustling and brilliant while surrounded by a lineup of girls with booming personalities like Hotaru Amano, the sharp tongued, half-Japanese beauty, and Alice Kamishiro, the lazy witch who loves modern-science and mail-orders. Eventually, our protagonist is coaxed into joining the action committee for the academy's traditional beauty contest by his close friend. He interacts with the heroines participating in this contest who are cute but each have an idiocyncrasy or two. Fun events (with their own difficulties) pop up again and again. Your story with 'her' about smiles, peace, passion, and love, all while borrowing the power of a witch, is about to begin! 'Supipara - Alice the Magical Conductor.' is an interactive novel themed around 'dynamicism' depicted through a rallying all of the production techniques minori has accumulated to date. See expressive character portraits with moving eyes, mouths, even hair! It is quite immersive in many aspects. Also, 'Supipara' won't conclude in a single game. It will be released as several standalone episodes. Fans may freely pursue only the episodes that interest them if so desired. You could say 'it's a light novel series, and independent stories which develop their own unique personalities all in one.'
2   Springtime, April: when the cherry trees come into full bloom. The protagonist Yukinari Sanada has returned to his hometown in Kanagawa Prefecture, Kamakura City, for the first time in seven years, and is greeted by his older cousin Sakura Narumi (complete with maid outfit). He wanted to live in peace, but his life at the academy placed on the coastlands becomes bustling and brilliant while surrounded by a lineup of girls with booming personalities like Hotaru Amano, the sharp tongued, half-Japanese beauty, and Alice Kamishiro, the lazy witch who loves modern-science and mail-orders. Eventually, our protagonist is coaxed into joining the action committee for the academy's traditional beauty contest by his close friend. He interacts with the heroines participating in this contest who are cute but each have an idiocyncrasy or two. Fun events (with their own difficulties) pop up again and again. Your story with 'her' about smiles, peace, passion, and love, all while borrowing the power of a witch, is about to begin! 'Supipara - Alice the Magical Conductor.' is an interactive novel themed around 'dynamicism' depicted through a rallying all of the production techniques minori has accumulated to date. See expressive character portraits with moving eyes, mouths, even hair! It is quite immersive in many aspects. Also, 'Supipara' won't conclude in a single game. It will be released as several standalone episodes. Fans may freely pursue only the episodes that interest them if so desired. You could say 'it's a light novel series, and independent stories which develop their own unique personalities all in one.'
4   Springtime, April: when the cherry trees come into full bloom. The protagonist Yukinari Sanada has returned to his hometown in Kanagawa Prefecture, Kamakura City, for the first time in seven years, and is greeted by his older cousin Sakura Narumi (complete with maid outfit). He wanted to live in peace, but his life at the academy placed on the coastlands becomes bustling and brilliant while surrounded by a lineup of girls with booming personalities like Hotaru Amano, the sharp tongued, half-Japanese beauty, and Alice Kamishiro, the lazy witch who loves modern-science and mail-orders. Eventually, our protagonist is coaxed into joining the action committee for the academy's traditional beauty contest by his close friend. He interacts with the heroines participating in this contest who are cute but each have an idiocyncrasy or two. Fun events (with their own difficulties) pop up again and again. Your story with 'her' about smiles, peace, passion, and love, all while borrowing the power of a witch, is about to begin! 'Supipara - Alice the Magical Conductor.' is an interactive novel themed around 'dynamicism' depicted through a rallying all of the production techniques minori has accumulated to date. See expressive character portraits with moving eyes, mouths, even hair! It is quite immersive in many aspects. Also, 'Supipara' won't conclude in a single game. It will be released as several standalone episodes. Fans may freely pursue only the episodes that interest them if so desired. You could say 'it's a light novel series, and independent stories which develop their own unique personalities all in one.'
5   Springtime, April: when the cherry trees come into full bloom. The protagonist Yukinari Sanada has returned to his hometown in Kanagawa Prefecture, Kamakura City, for the first time in seven years, and is greeted by his older cousin Sakura Narumi (complete with maid outfit). He wanted to live in peace, but his life at the academy placed on the coastlands becomes bustling and brilliant while surrounded by a lineup of girls with booming personalities like Hotaru Amano, the sharp tongued, half-Japanese beauty, and Alice Kamishiro, the lazy witch who loves modern-science and mail-orders. Eventually, our protagonist is coaxed into joining the action committee for the academy's traditional beauty contest by his close friend. He interacts with the heroines participating in this contest who are cute but each have an idiocyncrasy or two. Fun events (with their own difficulties) pop up again and again. Your story with 'her' about smiles, peace, passion, and love, all while borrowing the power of a witch, is about to begin! 'Supipara - Alice the Magical Conductor.' is an interactive novel themed around 'dynamicism' depicted through a rallying all of the production techniques minori has accumulated to date. See expressive character portraits with moving eyes, mouths, even hair! It is quite immersive in many aspects. Also, 'Supipara' won't conclude in a single game. It will be released as several standalone episodes. Fans may freely pursue only the episodes that interest them if so desired. You could say 'it's a light novel series, and independent stories which develop their own unique personalities all in one.'
10  Springtime, April: when the cherry trees come into full bloom. The protagonist Yukinari Sanada has returned to his hometown in Kanagawa Prefecture, Kamakura City, for the first time in seven years, and is greeted by his older cousin Sakura Narumi (complete with maid outfit). He wanted to live in peace, but his life at the academy placed on the coastlands becomes bustling and brilliant while surrounded by a lineup of girls with booming personalities like Hotaru Amano, the sharp tongued, half-Japanese beauty, and Alice Kamishiro, the lazy witch who loves modern-science and mail-orders. Eventually, our protagonist is coaxed into joining the action committee for the academy's traditional beauty contest by his close friend. He interacts with the heroines participating in this contest who are cute but each have an idiocyncrasy or two. Fun events (with their own difficulties) pop up again and again. Your story with 'her' about smiles, peace, passion, and love, all while borrowing the power of a witch, is about to begin! 'Supipara - Alice the Magical Conductor.' is an interactive novel themed around 'dynamicism' depicted through a rallying all of the production techniques minori has accumulated to date. See expressive character portraits with moving eyes, mouths, even hair! It is quite immersive in many aspects. Also, 'Supipara' won't conclude in a single game. It will be released as several standalone episodes. Fans may freely pursue only the episodes that interest them if so desired. You could say 'it's a light novel series, and independent stories which develop their own unique personalities all in one.'
11  Springtime, April: when the cherry trees come into full bloom. The protagonist Yukinari Sanada has returned to his hometown in Kanagawa Prefecture, Kamakura City, for the first time in seven years, and is greeted by his older cousin Sakura Narumi (complete with maid outfit). He wanted to live in peace, but his life at the academy placed on the coastlands becomes bustling and brilliant while surrounded by a lineup of girls with booming personalities like Hotaru Amano, the sharp tongued, half-Japanese beauty, and Alice Kamishiro, the lazy witch who loves modern-science and mail-orders. Eventually, our protagonist is coaxed into joining the action committee for the academy's traditional beauty contest by his close friend. He interacts with the heroines participating in this contest who are cute but each have an idiocyncrasy or two. Fun events (with their own difficulties) pop up again and again. Your story with 'her' about smiles, peace, passion, and love, all while borrowing the power of a witch, is about to begin! 'Supipara - Alice the Magical Conductor.' is an interactive novel themed around 'dynamicism' depicted through a rallying all of the production techniques minori has accumulated to date. See expressive character portraits with moving eyes, mouths, even hair! It is quite immersive in many aspects. Also, 'Supipara' won't conclude in a single game. It will be released as several standalone episodes. Fans may freely pursue only the episodes that interest them if so desired. You could say 'it's a light novel series, and independent stories which develop their own unique personalities all in one.'
12  Springtime, April: when the cherry trees come into full bloom. The protagonist Yukinari Sanada has returned to his hometown in Kanagawa Prefecture, Kamakura City, for the first time in seven years, and is greeted by his older cousin Sakura Narumi (complete with maid outfit). He wanted to live in peace, but his life at the academy placed on the coastlands becomes bustling and brilliant while surrounded by a lineup of girls with booming personalities like Hotaru Amano, the sharp tongued, half-Japanese beauty, and Alice Kamishiro, the lazy witch who loves modern-science and mail-orders. Eventually, our protagonist is coaxed into joining the action committee for the academy's traditional beauty contest by his close friend. He interacts with the heroines participating in this contest who are cute but each have an idiocyncrasy or two. Fun events (with their own difficulties) pop up again and again. Your story with 'her' about smiles, peace, passion, and love, all while borrowing the power of a witch, is about to begin! 'Supipara - Alice the Magical Conductor.' is an interactive novel themed around 'dynamicism' depicted through a rallying all of the production techniques minori has accumulated to date. See expressive character portraits with moving eyes, mouths, even hair! It is quite immersive in many aspects. Also, 'Supipara' won't conclude in a single game. It will be released as several standalone episodes. Fans may freely pursue only the episodes that interest them if so desired. You could say 'it's a light novel series, and independent stories which develop their own unique personalities all in one.'

   Supported languages Full audio languages Reviews  \
1          ['English']                   []     NaN
2          ['English']                   []     NaN
4          ['English']                   []     NaN
5          ['English']                   []     NaN
10         ['English']                   []     NaN
11         ['English']                   []     NaN
12         ['English']                   []     NaN

                                                                                         Header image  \
1   https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/header.jpg?t=1725519097
2   https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/header.jpg?t=1725519097
4   https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/header.jpg?t=1725519097
5   https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/header.jpg?t=1725519097
10  https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/header.jpg?t=1725519097
11  https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/header.jpg?t=1725519097
12  https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/496350/header.jpg?t=1725519097

                           Website            Support url  \
1   http://mangagamer.org/supipara  http://mangagamer.com
2   http://mangagamer.org/supipara  http://mangagamer.com
4   http://mangagamer.org/supipara  http://mangagamer.com
5   http://mangagamer.org/supipara  http://mangagamer.com
10  http://mangagamer.org/supipara  http://mangagamer.com
11  http://mangagamer.org/supipara  http://mangagamer.com
12  http://mangagamer.org/supipara  http://mangagamer.com

             Support email  Windows    Mac  Linux  Metacritic score  \
1   support@mangagamer.com     True  False  False                 0
2   support@mangagamer.com     True  False  False                 0
4   support@mangagamer.com     True  False  False                 0
5   support@mangagamer.com     True  False  False                 0
10  support@mangagamer.com     True  False  False                 0
11  support@mangagamer.com     True  False  False                 0
12  support@mangagamer.com     True  False  False                 0

   Metacritic url  User score  Positive  Negative  Score rank  Achievements  \
1             NaN           0       252         3         NaN             0
2             NaN           0       252         3         NaN             0
4             NaN           0       252         3         NaN             0
5             NaN           0       252         3         NaN             0
10            NaN           0       252         3         NaN             0
11            NaN           0       252         3         NaN             0
12            NaN           0       252         3         NaN             0

    Recommendations Notes  Average playtime forever  \
1               231   NaN                         8
2               231   NaN                         8
4               231   NaN                         8
5               231   NaN                         8
10              231   NaN                         8
11              231   NaN                         8
12              231   NaN                         8

    Average playtime two weeks  Median playtime forever  \
1                            0                        8
2                            0                        8
4                            0                        8
5                            0                        8
10                           0                        8
11                           0                        8
12                           0                        8

    Median playtime two weeks Developers  Publishers  \
1                           0     minori  MangaGamer
2                           0     minori  MangaGamer
4                           0     minori  MangaGamer
5                           0     minori  MangaGamer
10                          0     minori  MangaGamer
11                          0     minori  MangaGamer
12                          0     minori  MangaGamer

                                                      Categories     Genres  \
1   Single-player,Steam Trading Cards,Steam Cloud,Family Sharing  Adventure
2   Single-player,Steam Trading Cards,Steam Cloud,Family Sharing  Adventure
4   Single-player,Steam Trading Cards,Steam Cloud,Family Sharing  Adventure
5   Single-player,Steam Trading Cards,Steam Cloud,Family Sharing  Adventure
10  Single-player,Steam Trading Cards,Steam Cloud,Family Sharing  Adventure
11  Single-player,Steam Trading Cards,Steam Cloud,Family Sharing  Adventure
12  Single-player,Steam Trading Cards,Steam Cloud,Family Sharing  Adventure

                                 Tags  \
1   Adventure,Visual Novel,Anime,Cute
2   Adventure,Visual Novel,Anime,Cute
4   Adventure,Visual Novel,Anime,Cute
5   Adventure,Visual Novel,Anime,Cute
10  Adventure,Visual Novel,Anime,Cute
11  Adventure,Visual Novel,Anime,Cute
12  Adventure,Visual Novel,Anime,Cute


In [23]:
eval_df[
    [
        "user_id",
        "app_id",
        "Name",
        "Genres",
        "Tags",
        "is_recommended",
        "hours"
    ]
].head(10)

,user_id,app_id,Name,Genres,Tags,is_recommended,hours
1,7177628,496350,Supipara - Chapter 1 Spring Has Come!,Adventure,"Adventure,Visual Novel,Anime,Cute",True,25.0
2,10659614,496350,Supipara - Chapter 1 Spring Has Come!,Adventure,"Adventure,Visual Novel,Anime,Cute",True,4.0
4,8508352,496350,Supipara - Chapter 1 Spring Has Come!,Adventure,"Adventure,Visual Novel,Anime,Cute",True,10.0
5,7112108,496350,Supipara - Chapter 1 Spring Has Come!,Adventure,"Adventure,Visual Novel,Anime,Cute",True,46.0
10,10349601,496350,Supipara - Chapter 1 Spring Has Come!,Adventure,"Adventure,Visual Novel,Anime,Cute",True,0.0
11,6066119,496350,Supipara - Chapter 1 Spring Has Come!,Adventure,"Adventure,Visual Novel,Anime,Cute",True,2.0
12,5944835,496350,Supipara - Chapter 1 Spring Has Come!,Adventure,"Adventure,Visual Novel,Anime,Cute",True,505.0
13,4450098,496350,Supipara - Chapter 1 Spring Has Come!,Adventure,"Adventure,Visual Novel,Anime,Cute",True,12.0
14,14988,496350,Supipara - Chapter 1 Spring Has Come!,Adventure,"Adventure,Visual Novel,Anime,Cute",True,39.0
15,5552167,496350,Supipara - Chapter 1 Spring Has Come!,Adventure,"Adventure,Visual Novel,Anime,Cute",True,17.0

In [35]:
print(eval_df.shape)
print(eval_df["user_id"].nunique())

(12165200, 47)
647035

In [36]:
from sklearn.model_selection import train_test_split
import pandas as pd

train_list = []
test_list = []

# 사용자별 30%를 Test로 추출
test_df = (
    eval_df.groupby("user_id", group_keys=False)
           .sample(frac=0.3, random_state=42)
)

# 나머지를 Train으로 사용
train_df = eval_df.drop(test_df.index)

print(train_df.shape)
print(test_df.shape)

(8531170, 47)
(3634030, 47)

In [41]:
train_df.to_csv(
    r"C:\projects\Game-Recommendation-System\data\split\train.csv",
    index=False,
    encoding="utf-8-sig"
)

test_df.to_csv(
    r"C:\projects\Game-Recommendation-System\data\split\test.csv",
    index=False,
    encoding="utf-8-sig"
)

In [37]:
print(eval_df.dtypes)

app_id                          int64
Name                              str
Release date                      str
Estimated owners                  str
Peak CCU                        int64
Required age                    int64
Price                         float64
Discount                        int64
DLC count                       int64
About the game                    str
Supported languages               str
Full audio languages              str
Reviews                           str
Header image                      str
Website                           str
Support url                       str
Support email                     str
Windows                          bool
Mac                              bool
Linux                            bool
Metacritic score                int64
Metacritic url                    str
User score                      int64
Positive                        int64
Negative                        int64
Score rank                    float64
Achievements                    int64
Recommendations                 int64
Notes                             str
Average playtime forever        int64
Average playtime two weeks      int64
Median playtime forever         int64
Median playtime two weeks       int64
Developers                        str
Publishers                        str
Categories                        str
Genres                            str
Tags                              str
Screenshots                       str
Movies                        float64
helpful                         int64
funny                           int64
date                              str
is_recommended                   bool
hours                         float64
user_id                         int64
review_id                       int64
dtype: object

In [ ]:


for user_id, user_data in eval_df.groupby("user_id"):

    print(f"\n===== User {user_id} =====")
    print(user_data.reset_index(drop=True)[ 
        ["app_id", "Name", "is_recommended", "hours"]
    ])

    count += 1

    if count == 5:
        break

===== User 0 =====
           app_id                                                                               Name  is_recommended  hours
2477804    418950                                                      DreadOut: Keepers of The Dark           False    5.0
5339726   1454400                                                                     Cookie Clicker            True  762.6
5446718    357900                                                                     Make it indie!           False    1.0
8787485    222880                                                                         Insurgency            True  162.5
9983261    226960                                                                   Ironclad Tactics           False    1.0
12410109    63710                                                                    BIT.TRIP RUNNER           False    2.0
13287619   487370                                                                               Akin           False    9.5
13662168   286360                                              Shadows on the Vatican - Act I: Greed            True    8.5
13901216    49520                                                                      Borderlands 2            True    2.1
16062586   602890                                                                          hack_me 2           False    1.5
17722412   365300                                                         Transmissions: Element 120           False    2.0
18654268   202750                                                     Alan Wake's American Nightmare           False   10.5
21735119   235540                                                  Warhammer: End Times - Vermintide            True   21.9
21837186   402840                                                        Crusaders of the Lost Idols            True  157.4
22977769   267060                                                                    Gravity Badgers           False   11.5
23776128   214490                                                                   Alien: Isolation            True   40.5
24067471   269790                                                                           DreadOut           False   13.5
25645133   539450                                                                           Crab Dub           False    5.5
27451341   451880                                                               Catch a Falling Star           False    6.5
27624982   260230  Valiant Hearts: The Great War™ / Soldats Inconnus : Mémoires de la Grande Guerre™           False    5.5
28314174   627690                                             Idle Champions of the Forgotten Realms            True  103.3
31237371   423880                                                                         Carpe Diem           False    1.0
33277737     8850                                                                        BioShock® 2            True   61.5
33843990   526740                                                                            hack_me           False    1.5
35671243   221910                                                                The Stanley Parable            True   19.6
38644677   591960                                           Animation Throwdown: The Quest for Cards           False   50.5
39798001   339160                                                Tales of the Orient: The Rising Sun           False   13.0

===== User 36 =====
           app_id                                        Name  is_recommended  hours
2382738   1290000                         PowerWash Simulator           False   30.5
6587975      4500         S.T.A.L.K.E.R.: Shadow of Chernobyl            True    4.9
9352103    412020                                Metro Exodus           False   16.9
17398160   239030                              Papers, Please            True   20.6
18685000    17470                           Dead Space (2008)           False    1.0
21615689  1172380               STAR WARS Jedi: Fallen Order™            True   24.7
21871133   534380  Dying Light 2 Stay Human: Reloaded Edition            True   67.9
27395733   246900                      Viscera Cleanup Detail            True  123.3
32208670  1174180                       Red Dead Redemption 2            True    9.3
33102903  1302240                                Labyrinthine            True    7.1
33251657   509980                                     BIGFOOT            True   34.5
35811378  1593500                                  God of War            True   22.0
35991800   301640                         Zombie Army Trilogy            True    2.0

===== User 99 =====
           app_id                           Name  is_recommended  hours
1622267    558990                    Opus Magnum            True   50.7
4795783    266510                   Hand of Fate            True   38.1
8944390   1054800                   变量 Variables            True   39.8
15024931   718670              Cultist Simulator            True   47.1
15483328   601840                     Griftlands            True   66.7
19309571  1468810          鬼谷八荒 Tale of Immortal           False   44.0
22888329   994280                 Gujian3(古剑奇谭三)            True   67.3
29504721  1094520               Sands of Salzaar            True   16.5
39204226   243970                Invisible, Inc.            True   49.7
39694937   632470  Disco Elysium - The Final Cut            True   50.5

===== User 181 =====
           app_id                                     Name  is_recommended  hours
898904     979710                                Easy Pose            True   24.3
2079401    252490                                     Rust            True  183.1
2130041    493900                               Dungeons 3            True   57.3
5487154    253230                            A Hat in Time            True   20.0
5910919    453090                                Parkitect            True   33.5
7166481    368950  Jigoku Kisetsukan: Sense of the Seasons            True    1.7
13973920   376300                   GUILTY GEAR Xrd -SIGN-            True   11.9
16500436   245170                    Skullgirls 2nd Encore            True   15.4
17138749    37000                                 The Void            True    1.0
18400492   221100                                     DayZ            True  191.3
18443991  1369340                    Cats Organized Neatly            True    1.5
21938726   774171                                Muse Dash            True    9.3
24314598   391540                                Undertale            True   10.4
30558245   860510                     Little Nightmares II            True    7.3
32771813   962130                                 Grounded            True   34.6
39385512   365590               Tom Clancy’s The Division™            True  120.6

===== User 191 =====
           app_id                   Name  is_recommended  hours
4168241    105600               Terraria            True   31.5
16757131   435790      10 Second Ninja X            True    3.2
19543071      440        Team Fortress 2            True  275.0
20005646   444200   World of Tanks Blitz            True   15.8
22295059   213610      Sonic Adventure 2            True    2.8
23499122   871720  Ultimate Custom Night            True    3.5
24610303  1046930        Dota Underlords            True   51.3
29870619   219740           Don't Starve            True   67.9
32017951   268910                Cuphead            True   15.6
32060175   322170          Geometry Dash            True   97.6
34945835   291550             Brawlhalla            True   82.2
38037367   471710               Rec Room            True    8.0
38602422    71250     Sonic Adventure DX            True   22.1
40150793  1961460      PROJECT: PLAYTIME           False    8.4

In [3]:
print(recommendations.head())

    app_id  helpful  funny        date  is_recommended  hours  user_id  \
0   975370        0      0  2022-12-12            True   36.3    51580
1   304390        4      0  2017-02-17           False   11.5     2586
2  1085660        2      0  2019-11-17            True  336.5   253880
3   703080        0      0  2022-09-23            True   27.4   259432
4   526870        0      0  2021-01-10            True    7.9    23869

   review_id
0          0
1          1
2          2
3          3
4          4

In [4]:
print(gamesgenres.head())

     AppID                                   Name  Release date  \
0  2539430             Black Dragon Mage Playtest   Aug 1, 2023
1   496350  Supipara - Chapter 1 Spring Has Come!  Jul 29, 2016
2  1034400      Mystery Solitaire The Black Raven   May 6, 2019
3  3292190            버튜버 파라노이아 - Vtuber Paranoia  Oct 31, 2024
4  3631080                          Maze Quest VR  Apr 24, 2025

  Estimated owners  Peak CCU  Required age  Price  Discount  DLC count  \
0            0 - 0         0             0   0.00         0          0
1        0 - 20000         0             0   5.24        65          0
2        0 - 20000         0             0   4.99         0          0
3        0 - 20000         1             0   8.99         0          1
4        0 - 20000         0             0   4.99         0          0

                                      About the game  ...  \
0                                                NaN  ...
1  Springtime, April: when the cherry trees come ...  ...
2  Immerse yourself in the most beloved, mystical...  ...
3  synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...  ...
4  Its not just a Maze; its a Quest! Enter the ca...  ...

  Average playtime two weeks Median playtime forever  \
0                          0                       0
1                          0                       8
2                          0                       0
3                          0                       0
4                          0                       0

  Median playtime two weeks            Developers            Publishers  \
0                         0                   NaN                   NaN
1                         0                minori            MangaGamer
2                         0           Somer Games                8floor
3                         0                 유진게임즈                 유진게임즈
4                         0  Reality Expanded LLC  Reality Expanded LLC

                                          Categories                   Genres  \
0                                                NaN                      NaN
1  Single-player,Steam Trading Cards,Steam Cloud,...                Adventure
2                       Single-player,Family Sharing                   Casual
3    Single-player,Steam Achievements,Family Sharing  Casual,Indie,Simulation
4  Single-player,VR Only,Steam Leaderboards,Famil...      Action,Early Access

                                                Tags  \
0                                                NaN
1                  Adventure,Visual Novel,Anime,Cute
2  Casual,Card Game,Solitaire,Puzzle,Hidden Objec...
3                                                NaN
4                                                NaN

                                         Screenshots  Movies
0  https://shared.akamai.steamstatic.com/store_it...     NaN
1  https://shared.akamai.steamstatic.com/store_it...     NaN
2  https://shared.akamai.steamstatic.com/store_it...     NaN
3  https://shared.akamai.steamstatic.com/store_it...     NaN
4  https://shared.akamai.steamstatic.com/store_it...     NaN

[5 rows x 40 columns]